#!/usr/bin/env bash

LOGFILE=.lc.log
DMENU="rofi -dmenu"

Commands="s suspend goto common pass set-keyboard poweroff lock scrot region overleaf-render caps-lock win wall cups pass sync"

handle_stuff() {
	if [ "$1" = "--dmenu" ]; then
		$0 $(echo $Commands | tr " " "\n" | $DMENU -i -p "lc")
	fi

# System maintenance
	if [ "$1" = "sk" ] || [ "$1" = "set-keyboard" ]; then
		setxkbmap -layout us -variant altgr-intl
		#xcape -e "Control_R=Escape"
		xmodmap .Xmodmap
	fi

# POWER COMMANDS
	if [ "$1" = "suspend" ]; then
		systemctl suspend
	fi
	if [ "$1" = "poweroff" ]; then
		poweroff
	fi
	if [ "$1" = "lock" ]; then
        $HOME/Scripts/lock.sh
	fi

# Mics
	if [ "$1" = "scrot" ]; then
		scrot /tmp/%Y-%m-%d-%T-screenshot.png
	fi
	if [ "$1" = "region" ]; then
        import /tmp/$(date -Iseconds)-screenshot.png
	fi

	if [ "$1" = "overleaf-render" ]; then
		st sh ~/Documents/overleafRenderer/compile.sh
	fi

	if [ "$1" = "caps-lock" ]; then
		xdotool key Caps_Lock
	fi

	if [ "$1" = "win" ]; then
		vboxmanage startvm "Windows xp"
	fi

	if [ "$1" = "wall" ]; then
		$HOME/Scripts/setwall -A
	fi

# Launch
    if [ "$1" = "s" ]; then
        $HOME/Scripts/guiworkspace.sh
    fi

	if [ "$1" = "cups" ] || [ "$1" = "cups-website" ]; then
		firefox "http://localhost:631/"
	fi

	if [ "$1" = "pass" ]; then
		bash $HOME/Scripts/passmenu --type
	fi

	if [ "$1" = "common" ]; then
		python3 Scripts/commondocs.py ~/commondocs.json $(python3 Scripts/commondocs.py ~/commondocs.json | $DMENU)
	fi

    if [ "$1" = "sync" ]; then
        ./Scripts/sync.sh
        dunstify "Sync complete" "Sync completed at $(date)"
    fi

    if [ "$1" = "goto" ]; then
        caja $(./Scripts/goto -d $(cat .bookmarks | awk -F ' ' '{print $1}' | $DMENU))
    fi

# Calc
	if [ "$(echo $1 | head -c 1)" = "=" ]; then
		calc="$(echo $1 | cut -c 2-)"
		notify-send "Result" "$calc = $(echo $calc | bc)"
	fi
}


handle_stuff $* 2>&1 | tee -a $LOGFILE
