#!/usr/bin/env bash

plctl_flags="-i chromium,firefox"

case $1 in
    micmutetoggle)
        pacmd set-source-mute @DEFAULT_SOURCE@ toggle
        ;;
    softmute)
        pacmd set-source-volume @DEFAULT_SOURCE@ 0
        ;;
    softunmute)
        pacmd set-source-volume @DEFAULT_SOURCE@ 69000
        ;;
    volumedown)
        pactl set-sink-volume @DEFAULT_SINK@ -2%
        ;;
    volumeup)
        pactl set-sink-volume @DEFAULT_SINK@ +2%
        ;;
    volumetoggle)
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        ;;

    playtoggle)
        playerctl $plctl_flags play-pause
        ;;
    forward)
        playerctl $plctl_flags next
        ;;
    backward)
        playerctl $plctl_flags previous
        ;;
esac
