#!/usr/bin/env bash

case $1 in
    micmutetoggle)
        pacmd set-source-mute @DEFAULT_SOURCE@ toggle
        ;;
    softmute)
        pacmd set-source-volume @DEFAULT_SOURCE@ 0
        ;;
    softunmute)
        pacmd set-source-volume @DEFAULT_SOURCE@ 38000
        ;;
    volumedown)
        pactl set-sink-volume @DEFAULT_SINK@ -5%
        ;;
    volumeup)
        pactl set-sink-volume @DEFAULT_SINK@ +5%
        ;;
    volumetoggle)
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        ;;

    playtoggle)
        playerctl play-pause
        ;;
    forward)
        playerctl next
        ;;
    backward)
        playerctl previous
        ;;
esac
