#! /usr/bin/env bash

# Started by nixos
# sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width		3
bspc config window_gap			12

bspc config split_ratio			0.52
bspc config borderless_monocle	true
bspc config gapless_monocle		true
bspc config single_monocle false

bspc config bottom_padding 16

bspc config pointer_modifier mod1

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# Just some rules
bspc rule -a evolution desktop=^8
bspc rule -a firefox desktop=^9

# Colors
bspc config normal_border_color "#555753"
bspc config active_border_color "#555753"
bspc config focused_border_color "#3465a4"

# Launch other stuff
~/Scripts/xlaunchrc
