#! /usr/bin/env bash

# Started by nixos
# sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width		1
bspc config window_gap			0

bspc config split_ratio			0.52
bspc config borderless_monocle	true
bspc config gapless_monocle		true
bspc config single_monocle false

bspc config pointer_modifier mod4

bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors true

# Just some rules
bspc rule -a firefox desktop=^9
bspc rule -a float state=floating
bspc rule -a oneko state=floating

# Colors
bspc config normal_border_color "#FE6D73"
bspc config active_border_color "#F3B61F"
bspc config focused_border_color "#A0031D"
