#!/bin/bash

#Name: pacman.sh
#This is a pacman script for archlinux users on ubuntu
#Autor: Stjepan Horvat aka schef
#Date: 2011-05-13

USAGE="Usage: Arch Linux like pacman."

if [ $# -eq 0 ]; then
  echo $USAGE
  exit
elif [ $# -gt 2 ];then
  echo $USAGE
  exit

elif [ $1 = -Ss ]; then
  apt search $2

elif [ $1 = -S ]; then
  apt install $2

elif [ $1 = -Sy ]; then
  apt update

elif [ $1 = -Su ]; then
  apt upgrade

elif [ $1 = -Syu ]; then
  apt update && apt upgrade

else
  echo $USAGE
  exit
fi
