
# Lsp stuff
eval %sh{kak-lsp --kakoune -s %kak_session}

lsp-enable
map global user l %{: enter-user-mode lsp<ret>} -docstring "LSP mode"
# lsp-auto-hover-enable

# General stuff
colorscheme gruvbox-dark

hook global InsertChar \t %{ exec -draft -itersel h@ }
set global tabstop 2
set global indentwidth 2

map global insert <c-w> '<a-;><a-/>\S+\s*<ret><a-;>d'
map global insert <tab> '.<a-;>><backspace>'

add-highlighter global/matching show-matching
set-face global MatchingChar blue+b
add-highlighter global/lines number-lines -relative
add-highlighter global/tabs show-whitespaces -tab ">" -lf " " -nbsp " " -spc " "

add-highlighter global/wrap wrap
