#!/usr/bin/env bash

set -e

export _JAVA_AWT_WM_NONREPARENTING=1
export TERM=termite
export TERMINAL=termite

# export SSH_AUTH_SOCK=${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh

export XKB_DEFAULT_LAYOUT=us
export XKB_DEFAULT_VARIANT=altgr-intl

