#!/usr/bin/env bash
PIDFILE=/var/run/user/$UID/dwm.pid

kill $(<$PIDFILE)

if [ "$1" = "-e" ]; then
    exit
fi

echo $$ > $PIDFILE

$HOME/Software/slstatus/slstatus &

while true; do
    $HOME/Software/dwm/dwm >> /tmp/dwmsession.log
    sleep 1
done
